config/routes.rb
Rails.application.routes.draw do
  get "pages/dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#dashboard"
  get "receipts/photo", to: "receipts#new_photo", as: :new_photo_receipt
  post "receipts/photo", to: "receipts#create_photo", as: :create_photo_receipt
  resources :receipts
  resources :categories
end

app/views/shared/_side_bar.html.erb
<div class="w-1/3 p-4 bg-gray-200 ">
  <%= link_to "Budget Tracker", root_path, class: "rounded-lg py-3 px-5 bg-pink-800 text-white block font-medium" %>

  <div class="py-4">
    <%= link_to receipts_path do %>
      <h2 class="font-bold text-2xl pb-4">Receipt</h2>
    <% end %>
    <%= link_to "New receipt", new_receipt_path, class: "rounded-lg py-3 px-5 bg-indigo-800 text-white block font-medium" %>
    <%= link_to "New receipt by Photo", new_photo_receipt_path, class: "rounded-lg py-3 px-5 bg-indigo-800 text-white block font-medium" %>
  </div>

  <div class="py-4">
    <%= link_to categories_path do %>
      <h2 class="font-bold text-2xl pb-4">Categories</h2>
    <% end %>
    <ul class="pb-2">
      <% categories.each do |category| %>
        <li><%= link_to category.name, category %></li>
      <% end %>
    </ul>
    <%= link_to "New category", new_category_path, class: "rounded-lg py-3 px-5 bg-gray-400 text-white block font-medium" %>
  </div>
</div>