config/routes.rb
Rails.application.routes.draw do
  get "pages/dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#dashboard"
  get "receipts/photo", to: "receipts#new_photo", as: :new_photo_receipt
  post "receipts/photo", to: "receipts#create_photo", as: :create_photo_receipt
  resources :receipts
  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

  validates :name, presence: true
  validates :budget, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ChartDataHelper
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @bar_chart_data = bar_chart_data([ @category ])
    @pie_chart_data = @category.items.group(:name).sum(:amount)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :budget)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <tr>
    <td class="w-2/5">
      <%= link_to category, class: "rounded-lg bg-gray-100 inline-block font-medium" do %>
        <h2 class="font-bold text-2xl"><%= category.name %></h2>
      <% end %>
    </td>
    <td class="w-2/5 text-right <%= category.items.sum(:amount) > category.budget ? 'text-red-500' : 'text-green-500' %>">
      Total Spending <%= number_to_currency(category.items.sum(:amount), unit: '¥', precision: 0) %> / <%= number_to_currency(category.budget, unit: '¥', precision: 0) %>
    </td>
    <td class="w-1/5 text-right">
      <div class="flex justify-end items-center">
        <%= link_to "Edit", edit_category_path(category), class: "rounded-lg py-3 px-5 bg-yellow-500 text-white block font-medium" %>
        <%#= link_to "Delete", category, method: :delete, data: { confirm: "Are you sure?" }, class: "rounded-lg py-3 px-5 bg-red-500 text-white block font-medium ml-2" %>
      </div>
    </td>
  </tr>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for category do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="py-4">
    <%= f.input :name %>
    <%= f.input :budget %>
  </div>

  <div class="mt-3">
    <%= f.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <div class="p-3">
    <%= render "form", category: @category %>
  </div>

  <div class="py-5">
    <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="w-full p-6">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Categories" %>

  <div class="flex justify-between items-center py-4">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to "New category", new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="categories" class="min-w-full flex flex-col gap-2">
    <% @categories.each do |category| %>
      <table>
        <%= render category %>
      </table>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl py-2">New category</h1>

  <div class="p-3">
    <%= render "form", category: @category %>
  </div>

  <div class="py-5">
    <%= link_to "Back to categories", categories_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="mx-auto w-full flex p-4">
  <div class="w-full">
    <% if notice.present? %>
      < class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="flex justify-between items-center w-full">
      <span class="font-bold text-4xl"><%= @category.name %></span>
      <div>
        <%= link_to "Edit this category", edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>

    <p class="<%= @category.items.sum(:amount) > @category.budget ? 'text-red-500' : 'text-green-500' %>">
      Total Spending <%= number_to_currency(@category.items.sum(:amount), unit: '¥', precision: 0) %> / <%= number_to_currency(@category.budget, unit: '¥', precision: 0) %>
    </p>
    <%= pie_chart @pie_chart_data, title: "This month's spending" %>
    <%= bar_chart @bar_chart_data, stacked: true, library: {
    scales: {
      x: { stacked: true },
      y: {
        stacked: true
      }
    }
  } %>
    <h2>Purchases</h2>
    <table class="table-auto w-full">
      <thead>
        <tr>
          <th class="px-4 py-2">Date</th>
          <th class="px-4 py-2">Name</th>
          <th class="px-4 py-2">Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @category.items.each do |item| %>
          <tr>
            <td class="border px-4 py-2"><%= item.receipt.date.strftime("%B %d, %Y") %></td>
            <td class="border px-4 py-2"><%= item.name %></td>
            <td class="border px-4 py-2"><%= number_to_currency(item.amount, unit: '¥', precision: 0) %></td>
          </tr>
        <% end %>
      </tbody>
    </div>
  </div>