config/routes.rb
Rails.application.routes.draw do
  get "pages/dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#dashboard"
  get "receipts/photo", to: "receipts#new_photo", as: :new_photo_receipt
  post "receipts/photo", to: "receipts#create_photo", as: :create_photo_receipt
  resources :receipts
  resources :categories
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_many :items, dependent: :destroy
  has_one_attached :photo

  validates :store, presence: true
  validates :date, presence: true

  accepts_nested_attributes_for :items, allow_destroy: true

  default_scope { where(date: Date.current.beginning_of_month..Date.current.end_of_month) }
end

app/controllers/receipts_controller.rb
require "open-uri"
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: %i[ show edit update destroy ]

  # GET /receipts or /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1 or /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new; @receipt.items.build
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts or /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)
    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: "Receipt was successfully created." }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_photo
    @receipt = Receipt.new
  end

  def create_photo
    puts "uploading photo"
    photo = Cloudinary::Uploader.upload(params[:receipt][:photo])
    receipt_photo_url = photo["url"]
    puts "photo uploaded"
    puts "calling chatgpt"
    # https://platform.openai.com/docs/guides/vision?lang=curl
    response = chatgpt.chat(
      parameters: {
        model: "gpt-4o-mini",
        messages: [
          { role: "user", content: [
            { type: "text", text: receipt_parser_instruction },
            { type: "image_url", image_url: { url: receipt_photo_url, detail: "high" } } ] }
        ] }
      )
    content = response.dig("choices", 0, "message", "content")
    puts "response received"
    puts content

    parsed_receipt = JSON.parse(content)
    puts "see parsed receipt"
    puts parsed_receipt

    puts "creating receipt"
    @receipt = Receipt.new
    @receipt.store = parsed_receipt["store"]
    @receipt.date = parsed_receipt["date"]
    file = URI.open(photo["secure_url"])
    @receipt.photo.attach(io: file, filename: photo["original_filename"], content_type: photo["format"])
    @receipt.save
    parsed_receipt["items"].map do |item_info|
      item = Item.new
      item.receipt = @receipt
      item.name = item_info["name"]
      item.amount = item_info["amount"]

      category = Category.find_by(name: item_info["category"])
      category = Category.create(name: item_info["category"], budget: 0) if category.nil?
      item.category = category
      item.save
    end
    redirect_to receipt_path(@receipt)
    console
  end

  # PATCH/PUT /receipts/1 or /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: "Receipt was successfully updated." }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1 or /receipts/1.json
  def destroy
    @receipt.destroy!

    respond_to do |format|
      format.html { redirect_to receipts_path, status: :see_other, notice: "Receipt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def receipt_params
      params.require(:receipt).permit(:store, :date, :photo, items_attributes: %i[id name category_id amount _destroy])
    end

    def chatgpt
      @chatgpt ||= OpenAI::Client.new
    end

    def receipt_parser_instruction
      # multi-line string
      <<~INSTRUCTION
You are a AI assistant for a budget app.
I need you to analyze this receipt and return me a JSON with the receipt information and each item's information translated to ENGLISH.
If the Total in the receipt includes tax, please allocate tax to each item respectively.
the JSON needs to be in the following format and attributes:
{ store: name_of_the_store_on_the_receipt, date: date_of_the_receipt, items: [{name: item_name, category: category_name, amount: item_amount_including_tax}] }
return the JSON as a string only, not a code block and do not add any of your descriptive text
      INSTRUCTION
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= simple_form_for receipt do |f| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
        <% receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if receipt.photo.attached? %>
    <%= cl_image_tag(receipt.photo.key, width: 192, height: 192, crop: "fill") %>
  <% else %>
    <%= f.input :photo, as: :file %>
  <% end %>
  <%= f.input :store %>
  <%= f.input :date %>
  <div class="bg-gray-100" data-controller="nested-field">
    <h2 class="font-medium text-l" >Items</h2>
    <div class='p-2 flex flex-col gap-2' data-nested-field-target="fieldsContainer">
      <%= f.simple_fields_for :items do |item| %>
        <%= render 'item_fields', i: item %>
      <% end %>
    </div>
    <div class="rounded-lg m-1 py-1 px-3 bg-gray-600 text-white inline-block font-medium cursor-pointer" data-action="click->nested-field#add">
      Add item
    </div>
  </div>

  <div class="mt-3">
    <%= f.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/receipts/_item_fields.html.erb
<div class="bg-gray-200 p-1" data-nested-field-target="fields">
  <div class="flex justify-around gap-2">
    <%= i.input :name %>
    <%= i.association :category %>
    <%= i.input :amount %>
  </div>
  <%= i.input :_destroy, as: :boolean, label: 'Remove item' %>
</div>

app/views/receipts/_receipt.html.erb
<div id="<%= dom_id receipt %>">

  <div class="mx-auto w-full flex p-4 gap-2">
    <%  if receipt.photo.attached? %>
      <%= cl_image_tag(receipt.photo.key, width: 192, height: 192, crop: "fill") %>
    <% else %>
      <div class="w-48 h-48 bg-gray-500"></div>
    <% end %>

    <div class="grow">
      <h1 class="font-bold text-4xl"><%= receipt.store %></h1>
      <div class="flex justify-between">
        <h1 class="font-bold text-4xl"><%= receipt.date.strftime('%Y-%m-%d') %></h1>
        <h1 class="font-bold text-4xl"><%= number_to_currency(receipt.items.sum(:amount), unit: '¥', precision: 0) %></h1>
      </div>
      <div class="mt-4">
        <%= render 'items/items', items: receipt.items %>
      </div>
    </div>
  </div>

</div>

app/views/receipts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing receipt</h1>

  <div class="p-3">
    <%= render "form", receipt: @receipt %>
  </div>

  <div class="py-5">
    <%= link_to "Show this receipt", @receipt, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to receipts", receipts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/receipts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Receipts" %>

  <div class="flex justify-between items-center p-5">
    <h1 class="font-bold text-4xl">Receipts</h1>
    <%= link_to "New receipt", new_receipt_path, class: "rounded-lg py-3 px-5 bg-indigo-800 text-white block font-medium" %>
  </div>

  <div id="receipts" class="min-w-full p-5 flex flex-col gap-2">
    <% @receipts.each do |receipt| %>
      <div class="bg-gray-100 hover:bg-gray-200">
        <%= link_to receipt do  %>
          <%= render receipt %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/receipts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New receipt</h1>

  <div class="p-3">
    <%= render "form", receipt: @receipt %>
  </div>

  <div class="py-5">
    <%= link_to "Back to receipts", receipts_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/receipts/new_photo.html.erb
<%= simple_form_for @receipt, url: create_photo_receipt_path do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
        <% @receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :photo, as: :file %>

  <div class="mt-3">
    <%= f.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/receipts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @receipt %>

    <%= link_to "Edit this receipt", edit_receipt_path(@receipt), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to receipts", receipts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this receipt", @receipt, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "mt-2 rounded-lg py-3 px-5 bg-red-200 font-medium" %>
    </div>
  </div>
</div>